### PR TITLE
chore!: remove merkle library

### PR DESCRIPTION
**Pull request by cmwaters**
This reverts commit fdf1e920e58a838598c959315a5c50b7f0ee54ce.

Closes: https://github.com/celestiaorg/go-square/issues/39

### CODE REVIEW

**Comment by Wondertan** [comment]
Shoot, we haven't decided what we do instead.

**Comment by cmwaters** [comment]
> Shoot, we haven't decided what we do instead.

We're actually not using this library atm (we're still depending on the `merkle` library in `celestia-core`). I don't mind if we decide to spin out it's own repo, to make `merkle` it's own go.mod, or just leave it as is

**Comment by rootulp** [comment]
Note: there are usages of go-square/merkle in celestia-app (e.g. [here](https://github.com/celestiaorg/celestia-app/blob/941538c20bf30a62e3753a152bf87302f62ce529/pkg/da/data_availability_header.go#L9)) so I'm guessing those usages will need to be updated to celestia-core `merkle` instead when celestia-app bumps to go-square v2.

**Review by rootulp — APPROVED** [review]
Seems fine to me. In go-square v2 release notes we should provide guidance to any consumers who use go-square/merkle to migrate to something else (potentially celestia-core merkle)

**Review by cristaloleg — APPROVED** [review]
yay

**Review by Wondertan — CHANGES_REQUESTED** [review]
> Actually I'm wrong. We do use it so would have to revert back to celestia-core

Just saw the edit. I am strictly against go-square depending on celestia-core, even if the merkle pkg is a separate go.mod inside

**Comment by rootulp** [comment]
go-square doesn't need to depend on celestia-core b/c nothing breaks if we remove the `merkle` package in this repo.

**Comment by Wondertan** [comment]
> We do use it so would have to revert back to celestia-core

What does revert back mean?

**Comment by rootulp** [comment]
I think consumers of go-square/merkle would have to revert back to consuming it from celestia-core.

**Review by Wondertan — APPROVED** [review]
I see, I misunderstood the message then

**Pull request merged**
